/*
 * Copyright 2026 Morphe.
 * https://github.com/MorpheApp/morphe-patches
 *
 * See the included NOTICE file for GPLv3 Section 7 terms that apply to Morphe contributions.
 */

package app.morphe.patches.youtube.misc.aislist

import app.morphe.patcher.patch.bytecodePatch
import app.morphe.patches.shared.misc.litho.filter.addLithoFilter
import app.morphe.patches.shared.misc.settings.preference.InputType
import app.morphe.patches.shared.misc.settings.preference.NonInteractivePreference
import app.morphe.patches.shared.misc.settings.preference.PreferenceCategory
import app.morphe.patches.shared.misc.settings.preference.PreferenceScreenPreference
import app.morphe.patches.shared.misc.settings.preference.PreferenceScreenPreference.Sorting
import app.morphe.patches.shared.misc.settings.preference.SwitchPreference
import app.morphe.patches.shared.misc.settings.preference.TextPreference
import app.morphe.patches.youtube.layout.flyout.flyoutPatch
import app.morphe.patches.youtube.misc.extension.sharedExtensionPatch
import app.morphe.patches.youtube.misc.litho.filter.lithoFilterPatch
import app.morphe.patches.youtube.misc.navigation.navigationBarHookPatch
import app.morphe.patches.youtube.misc.playertype.playerTypeHookPatch
import app.morphe.patches.youtube.misc.settings.PreferenceScreen
import app.morphe.patches.youtube.misc.settings.settingsPatch
import app.morphe.patches.youtube.shared.Constants.COMPATIBILITY_YOUTUBE
import app.morphe.util.setExtensionIsPatchIncluded

private const val EXTENSION_FILTER =
    "Lapp/morphe/extension/youtube/patches/components/AiSListFilter;"
private const val EXTENSION_SUBMIT_CLASS =
    "Lapp/morphe/extension/youtube/patches/utils/AiSListSubmitDialog;"

@Suppress("unused")
val aiSListPatch = bytecodePatch(
    name = "AI channel filter",
    description = "Adds options to hide videos from channels flagged as AI-generated by the AiSList community list " +
            "and to report AI channels from the video menu."
) {
    dependsOn(
        sharedExtensionPatch,
        settingsPatch,
        lithoFilterPatch,
        navigationBarHookPatch,
        playerTypeHookPatch,
        flyoutPatch
    )

    compatibleWith(COMPATIBILITY_YOUTUBE)

    execute {
        PreferenceScreen.FEED.addPreferences(
            PreferenceScreenPreference(
                key = "morphe_hide_aislist_screen",
                sorting = Sorting.UNSORTED,
                preferences = setOf(
                    PreferenceCategory(
                        key = "morphe_hide_aislist_blocklist_category",
                        sorting = Sorting.UNSORTED,
                        preferences = setOf(
                            SwitchPreference(
                                key = "morphe_hide_aislist_blocklist_home",
                                titleKey = "morphe_hide_aislist_hide_home_title"
                            ),
                            SwitchPreference(
                                key = "morphe_hide_aislist_blocklist_search",
                                titleKey = "morphe_hide_aislist_hide_search_title"
                            )
                        )
                    ),
                    PreferenceCategory(
                        key = "morphe_hide_aislist_warnlist_category",
                        sorting = Sorting.UNSORTED,
                        preferences = setOf(
                            SwitchPreference(
                                key = "morphe_hide_aislist_warnlist_home",
                                titleKey = "morphe_hide_aislist_hide_home_title"
                            ),
                            SwitchPreference(
                                key = "morphe_hide_aislist_warnlist_search",
                                titleKey = "morphe_hide_aislist_hide_search_title"
                            )
                        )
                    ),
                    PreferenceCategory(
                        key = "morphe_aislist_submit_category",
                        sorting = Sorting.UNSORTED,
                        preferences = setOf(
                            SwitchPreference("morphe_aislist_submit_flyout_menu", summary = true),
                            TextPreference(
                                key = "morphe_aislist_submit_username",
                                inputType = InputType.TEXT
                            )
                        )
                    ),
                    PreferenceCategory(
                        key = "morphe_hide_aislist_stats_category",
                        titleKey = "morphe_hide_stats_category_title",
                        sorting = Sorting.UNSORTED,
                        preferences = emptySet(),
                        tag = "app.morphe.extension.youtube.settings.preference.AiSListStatsPreferenceCategory"
                    ),
                    PreferenceCategory(
                        key = "morphe_hide_aislist_about_category",
                        titleKey = "morphe_hide_about_category_title",
                        sorting = Sorting.UNSORTED,
                        preferences = setOf(
                            NonInteractivePreference(
                                key = "morphe_hide_aislist_about",
                                titleKey = "morphe_hide_aislist_screen_title",
                                tag = "app.morphe.extension.shared.settings.preference.BulletPointPreference"
                            ),
                            NonInteractivePreference(
                                key = "morphe_hide_aislist_attribution",
                                tag = "app.morphe.extension.shared.settings.preference.AiSListAttributionPreference",
                                selectable = true
                            )
                        )
                    )
                )
            )
        )

        addLithoFilter(EXTENSION_FILTER)

        setExtensionIsPatchIncluded(EXTENSION_SUBMIT_CLASS)
    }
}
